CREATE DATABASE GESTION_DE_PEDIDOS


CREATE TABLE CLIENTE (
IDCLIENTE INT IDENTITY (1,1) NOT NULL,
NOMBRE NVARCHAR (30) NOT NULL,
APELLIDO NVARCHAR (20) NOT NULL,
CORREOELECTRONICO NVARCHAR (30) NOT NULL,
TELEFONO NVARCHAR (20) NOT NULL,
DIRECCION NVARCHAR (20) NOT NULL,
PRIMARY KEY (IDCLIENTE),
);
CREATE TABLE PEDIDO (
IDPEDIDO INT IDENTITY (1,1) NOT NULL,
IDCLIENTE INT NOT NULL,
FECHA DATETIME NOT NULL,
TOTAL MONEY NOT NULL,
ESTADO NVARCHAR (20) NOT NULL,
PRIMARY KEY (IDPEDIDO),
FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);






insert into cliente values('Manuelito', 'Chorohuanca', 'chorehuanca@gmail.com', '+59156895623','Av. La Paz');
insert into cliente values('Roberto', 'Olivera', 'gatito@gmail.com', '+59145454512','Av. Los Molles');

select * from CLIENTE

insert into pedido values(1, '2022-03-12 09:20:00', 300,'En Proceso');
insert into PEDIDO values(2, '2022-02-01 14:00:00', 200, 'Completado');

select * from PEDIDO


